### ISSUE TITLE
to_records recurrsive not working

### ISSUE THREAD

**Issue by grizzly-monkey** [tonyg/erlang-rfc4627#19]
Hello @tonyg 

 cannot convert to record from json if record is nested.

eg. 

record 

```
-record(inputuser,{t= <<"TL_inputUserContact">>,
  user_id=null :: integer(),
  access_hash = null :: integer()}).

-record(getfulluser,{
  id= #inputuser{}}).
```

code =

```
JSONReqa = <<"{\"id\":{\"t\":\"TL_inputUserContact\",\"access_hash\":0,\"user_id\":143444}}">>,
 ?DEBUG("re quersd ~p",[JSONReqa]),
Object23=erlang:element(2,rfc4627:decode(JSONReqa))
?DEBUG("object = ~p",[Object23]),
?DEBUG("record = ~p",[?RFC4627_TO_RECORD(getfulluser,Object23)]),

```

output is 

```
 mod_contacts:gs().
18:38:04.695 [debug] re quersd <<"{\"id\":{\"t\":\"TL_inputUserContact\",\"access_hash\":0,\"user_id\":143444}}">>
18:38:04.697 [debug] object = {ok,{obj,[{"id",{obj,[{"t",<<"TL_inputUserContact">>},{"access_hash",0},{"user_id",143444}]}}]},[]}
18:38:04.697 [debug] object = {obj,[{"id",{obj,[{"t",<<"TL_inputUserContact">>},{"access_hash",0},{"user_id",143444}]}}]}
18:38:04.697 [debug] record = {getfulluser,{obj,[{"t",<<"TL_inputUserContact">>},{"access_hash",0},{"user_id",143444}]}}
{getfulluser,{obj,[{"t",<<"TL_inputUserContact">>},
                   {"access_hash",0},
                   {"user_id",143444}]}}
```

can @0x6e6562   @olcai  @tonyg  @paulj   @matwey   please help i really appreciate your help.

it should decode the inner record as well. any pointers will help.

**Comment by tonyg** [comment]
I don't think this is possible, because Erlang doesn't (or didn't, at the time the code was written - things may have changed) give access to enough reflective information about the expected types in each field of a record. All the code can do is loop over the _names_ of the fields in the record and pull out a corresponding field from the JSON object.

See [the manual page covering record_info](http://erlang.org/doc/reference_manual/records.html#id85431) to get an idea of the very limited amount of metadata we have to work with here.

You will have to write your own functions that perform any needed recursive decoding steps.
